config/routes.rb
Rails.application.routes.draw do
  root "customer#index"
  get "customer/alphabetized", to: "customer#alphabetized"
  get "customer/missing_email", to: "customer#missing_email"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    [ "created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at" ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image

  def self.ransackable_associations(auth_object = nil)
    [ "image_attachment", "image_blob" ]
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "created_at", "email_address", "full_name", "id", "notes", "phone_number", "updated_at", "image" ]
  end

  validates :full_name, :phone_number, :email_address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email: [ nil, "" ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customer/_customer.html.erb
<div class="column is-one-third">
  <% if customer.present? && customer.image.present? %>
    <div class="card-image">
      <figure class="image is-4by3">
        <%= image_tag customer.image %>
      </figure>
    </div>
  <% end %>
  <div class="card customer">
    <div class="card-content">
    <p class="title is-4">
      <% if name_is_link %>
        <%= link_to customer.full_name, customer %>
      <% else %>
        <%= customer.full_name %>
      <% end %>
    </p>
    <ul>
      <li>
        <strong>Phone Number:</strong> <%= customer.phone_number %>
      </li>
      <li>
        <strong>Email Address: </strong> <%= customer.email_address %>
      </li>
    </ul>
    </div>
  </div>
</div>

app/views/customer/alphabetized.html.erb
<h1>Alphabetized Customers</h1>
<%= link_to 'All Customers', root_path %> |
<%= link_to 'Customers Missing Emails', customer_missing_email_path %>

<% @customers.each do |customer| %>
  <%= render partial: 'customer', locals: { customer: customer } %>
<% end %>

app/views/customer/index.html.erb
<h1>All Customers</h1>
<%= link_to 'Alphabetized Customers', customer_alphabetized_path %> |
<%= link_to 'Customers Missing Emails', customer_missing_email_path %>

<% @customers.each do |customer| %>
  <%= render partial: "customer", locals: { customer: @customer, name_is_link: true } %>
<% end %>

app/views/customer/missing_email.html.erb
<h1>Customers Missing Email Addresses</h1>
<%= link_to 'All Customers', root_path %> |
<%= link_to 'Alphabetized Customers', customer_alphabetized_path %>

<% @customers.each do |customer| %>
  <%= render partial: 'customer', locals: { customer: customer } %>
<% end %>

app/views/customer/show.html.erb
<h1>Customer#show</h1>
<p>Find me in app/views/customer/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "U6 Millercortland" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>